In [75]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#### *Scaler*

In [76]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [77]:
scaler.ndimension()  # ndim

0

In [78]:
scaler.item()

7

#### *Vector*

In [79]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [80]:
vector.ndim

1

In [81]:
vector.shape

torch.Size([2])

#### Matrix

In [82]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [83]:
MATRIX.ndim

2

In [84]:
MATRIX[1]

tensor([ 9, 10])

In [85]:
MATRIX.shape

torch.Size([2, 2])

### Tensor

In [86]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [87]:
TENSOR.shape

torch.Size([1, 3, 3])

In [88]:
TENSOR.ndim

3

In [89]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensor

In [90]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9081, 0.0463, 0.4812, 0.6381],
        [0.5226, 0.6420, 0.0709, 0.0458],
        [0.4777, 0.3076, 0.3125, 0.6554]])

In [91]:
random_tensor.ndim

2

In [92]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))  # height, width, colour channel (RGB)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [93]:
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [94]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [95]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [96]:
one_to_ten = torch.arange(start=1, end=1000, step=77)
one_to_ten

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [97]:
tensor_like_zeros = torch.zeros_like(one_to_ten)
tensor_like_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])