In [113]:
from sndhdr import test_sndr

import torch
import numpy as np

#### *Scaler*

In [114]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [115]:
scaler.ndimension()  # ndim

0

In [116]:
scaler.item()

7

#### *Vector*

In [117]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [118]:
vector.ndim

1

In [119]:
vector.shape

torch.Size([2])

#### Matrix

In [120]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [121]:
MATRIX.ndim

2

In [122]:
MATRIX[1]

tensor([ 9, 10])

In [123]:
MATRIX.shape

torch.Size([2, 2])

### Tensor

In [124]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [125]:
TENSOR.shape

torch.Size([1, 3, 3])

In [126]:
TENSOR.ndim

3

In [127]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensor

In [128]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5745, 0.9200, 0.3230, 0.8613],
        [0.0919, 0.3102, 0.9536, 0.6002],
        [0.0351, 0.6826, 0.3743, 0.5220]])

In [129]:
random_tensor.ndim

2

In [130]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))  # height, width, color channel (RGB)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [131]:
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [132]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [133]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [134]:
one_to_ten = torch.arange(start=1, end=1000, step=77)
one_to_ten

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [135]:
tensor_like_zeros = torch.zeros_like(one_to_ten)
tensor_like_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [136]:
float_32_tensor = torch.tensor([3., 6., 9.],
                               dtype=None,
                               device=None,
                               requires_grad=False)  # requires_grad -> whether to track gradients on this tensor
float_32_tensor.dtype

torch.float32

In [137]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [138]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [139]:
int_64_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)

float_32_tensor * int_64_tensor

tensor([ 9., 36., 81.])

### Getting information from Tensors

In [140]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.5888, 0.8403, 0.4761, 0.7140],
        [0.4644, 0.6362, 0.8892, 0.1317],
        [0.7164, 0.2706, 0.6560, 0.6614]])

In [141]:
some_tensor.dtype, some_tensor.shape, some_tensor.device

(torch.float32, torch.Size([3, 4]), device(type='cpu'))

### Tensor Operations

In [142]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [143]:
tensor * 10

tensor([10, 20, 30])

In [144]:
tensor - 10

tensor([-9, -8, -7])

In [145]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [146]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [147]:
tensor * tensor

tensor([1, 4, 9])

In [148]:
torch.matmul(tensor, tensor)

tensor(14)

In [149]:
# Tensor Shape manipulation

A = torch.tensor([[1, 2],
                  [3, 4],
                  [5, 6]])
B = torch.tensor([[7, 10],
                  [8, 11],
                  [9, 12]])

In [150]:
# torch.mm(A,B)

In [151]:
B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [152]:
torch.mm(A, B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [153]:
# Min Max Mean
x = torch.arange(10, 100, 10)
x

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [154]:
torch.min(x), x.min()

(tensor(10), tensor(10))

In [155]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [156]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(50.), tensor(50.))

In [157]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [158]:
torch.argmax(x), x.argmax()

(tensor(8), tensor(8))

In [159]:
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

### Reshaping, view, stacking, squeezing, and unsqueezing

In [160]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [161]:
x.reshape(9, 1)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [162]:
z = x.view(1, 9)

In [163]:
# changing z also changes x, because .view() of a tensor shares the same memory as the original input
z[:, 0] = 5

In [164]:
z

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [165]:
x

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [166]:
torch.stack([x, x, x, x], dim=1)

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [167]:
torch.stack([x, x, x, x], dim=0)

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [168]:
x_reshaped = x.reshape([1, 9])

In [169]:
x_reshaped.shape

torch.Size([1, 9])

In [170]:
x_reshaped = x_reshaped.reshape((1, 9, 1))

In [171]:
x_reshaped.shape

torch.Size([1, 9, 1])

In [172]:
x_squeezed = x_reshaped.squeeze()

In [173]:
x_squeezed

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [174]:
x_reshaped.shape

torch.Size([1, 9, 1])

In [175]:
x_reshaped.ndim

3

In [176]:
x_reshaped.unsqueeze(dim=2).shape

torch.Size([1, 9, 1, 1])

### Permute

In [177]:
x = torch.rand(size=(224, 224, 3))
x.shape

torch.Size([224, 224, 3])

In [178]:
x_permuted = x.permute(2, 0, 1)

In [179]:
x_permuted.shape

torch.Size([3, 224, 224])

In [180]:
x.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [181]:
x_permuted[0, 0, 0] = 1

In [182]:
x[0, 0, 0]

tensor(1.)

In [183]:
# Permute also shares the same memory of the input, so changing x_permuted also changes x

### Indexing

In [184]:
x = torch.arange(1, 10).reshape(3, 1, 3)
x

tensor([[[1, 2, 3]],

        [[4, 5, 6]],

        [[7, 8, 9]]])

In [185]:
x[0]

tensor([[1, 2, 3]])

In [186]:
x[0, 0]

tensor([1, 2, 3])

In [187]:
x[0, 0, 0]

tensor(1)

In [188]:
x[1, 0, 1]

tensor(5)

In [189]:
x[:, :, 1]

tensor([[2],
        [5],
        [8]])

In [190]:
x[:, 0, :]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [191]:
x[0, 0, :]

tensor([1, 2, 3])

In [192]:
x[2, 0, 2]

tensor(9)

In [193]:
x[:, 0, 2]

tensor([3, 6, 9])

### pytorch and numpy

In [194]:
arr = np.arange(1., 8.)
tensor = torch.from_numpy(arr).type(torch.float32)

##### Note: _PyTorch's_ default dtype is `float32`, whereas _NumPy's_ default dtype is `float64`, so using `torch.from_numpy()` also makes the dtype `float64` use `.type(torch.float32)` to change back to default `float32`

In [195]:
arr.dtype, tensor.dtype

(dtype('float64'), torch.float32)

In [196]:
tensor = torch.ones(7)
numpy_arr = tensor.numpy()

In [197]:
tensor, numpy_arr

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [198]:
tensor.dtype, numpy_arr.dtype

(torch.float32, dtype('float32'))

##### Note: While changing _**NumPy**_ to _**PyTorch**_ (`torch.from_numpy(arr)`) or _**PyTorch**_ to _**NumPy**_ (`tensor.numpy()`), both the operations returns the _new items_ in the _memory_ with _new memory address_.

### Reproducibility (trying to taking out random out of random)

In [199]:
A = torch.rand(size=(3, 4))
B = torch.rand(size=(3, 4))

print(A)
print(B)
print(A == B)

tensor([[0.0022, 0.5045, 0.9239, 0.8234],
        [0.7196, 0.4880, 0.9011, 0.8759],
        [0.8584, 0.3418, 0.5555, 0.3992]])
tensor([[0.0235, 0.8930, 0.2409, 0.0920],
        [0.1770, 0.8702, 0.0014, 0.3203],
        [0.2243, 0.4263, 0.7375, 0.1651]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [200]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
D = torch.rand(3, 4)

print(C)
print(D)
print(C == D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### using GPU

In [201]:
!nvidia-smi

Thu Jun 18 13:53:46 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 610.47                 KMD Version: 610.47        CUDA UMD Version: 13.3     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   73C    P0             12W /   45W |     217MiB /   6144MiB |     24%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [219]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [220]:
tensor = torch.tensor([1, 2, 3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [221]:
tensor = tensor.to(device)
tensor, tensor.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

If a `tensor` is on `GPU` we can't convert it to `NumPy array`, because `NumPy` computes on `CPU` only

In [222]:
# tensor = tensor.numpy()

In [223]:
tensor = tensor.cpu()
tensor = tensor.numpy()
tensor

array([1, 2, 3])