In [396]:
import torch
import numpy as np

#### *Scaler*

In [172]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [173]:
scaler.ndimension()  # ndim

0

In [174]:
scaler.item()

7

#### *Vector*

In [175]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [176]:
vector.ndim

1

In [177]:
vector.shape

torch.Size([2])

#### Matrix

In [178]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [179]:
MATRIX.ndim

2

In [180]:
MATRIX[1]

tensor([ 9, 10])

In [181]:
MATRIX.shape

torch.Size([2, 2])

### Tensor

In [182]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [183]:
TENSOR.shape

torch.Size([1, 3, 3])

In [184]:
TENSOR.ndim

3

In [185]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensor

In [186]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7840, 0.6392, 0.4944, 0.2999],
        [0.4887, 0.4053, 0.0699, 0.2522],
        [0.1069, 0.4956, 0.9561, 0.7797]])

In [187]:
random_tensor.ndim

2

In [188]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))  # height, width, color channel (RGB)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [189]:
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [190]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [191]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [192]:
one_to_ten = torch.arange(start=1, end=1000, step=77)
one_to_ten

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [193]:
tensor_like_zeros = torch.zeros_like(one_to_ten)
tensor_like_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [194]:
float_32_tensor = torch.tensor([3., 6., 9.],
                               dtype=None,
                               device=None,
                               requires_grad=False)  # requires_grad -> whether to track gradients on this tensor
float_32_tensor.dtype

torch.float32

In [195]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [196]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [197]:
int_64_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)

float_32_tensor * int_64_tensor

tensor([ 9., 36., 81.])

### Getting information from Tensors

In [198]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.8529, 0.8401, 0.3156, 0.1016],
        [0.5278, 0.8854, 0.8134, 0.7248],
        [0.5939, 0.1618, 0.8490, 0.7327]])

In [199]:
some_tensor.dtype, some_tensor.shape, some_tensor.device

(torch.float32, torch.Size([3, 4]), device(type='cpu'))

### Tensor Operations

In [200]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [201]:
tensor * 10

tensor([10, 20, 30])

In [202]:
tensor - 10

tensor([-9, -8, -7])

In [203]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [204]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [205]:
tensor * tensor

tensor([1, 4, 9])

In [206]:
torch.matmul(tensor, tensor)

tensor(14)

In [207]:
# Tensor Shape manipulation

A = torch.tensor([[1, 2],
                  [3, 4],
                  [5, 6]])
B = torch.tensor([[7, 10],
                  [8, 11],
                  [9, 12]])

In [208]:
# torch.mm(A,B)

In [209]:
B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [210]:
torch.mm(A, B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [211]:
# Min Max Mean
x = torch.arange(10, 100, 10)
x

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [212]:
torch.min(x), x.min()

(tensor(10), tensor(10))

In [213]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [214]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(50.), tensor(50.))

In [215]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [216]:
torch.argmax(x), x.argmax()

(tensor(8), tensor(8))

In [217]:
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

### Reshaping, view, stacking, squeezing, and unsqueezing

In [218]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [219]:
x.reshape(9, 1)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [220]:
z = x.view(1, 9)

In [221]:
# changing z also changes x, because .view() of a tensor shares the same memory as the original input
z[:, 0] = 5

In [222]:
z

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [223]:
x

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [238]:
torch.stack([x, x, x, x], dim=1)

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [239]:
torch.stack([x, x, x, x], dim=0)

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [247]:
x_reshaped = x.reshape([1, 9])

In [248]:
x_reshaped.shape

torch.Size([1, 9])

In [277]:
x_reshaped = x_reshaped.reshape((1, 9, 1))

In [278]:
x_reshaped.shape

torch.Size([1, 9, 1])

In [279]:
x_squeezed = x_reshaped.squeeze()

In [280]:
x_squeezed

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [281]:
x_reshaped.shape

torch.Size([1, 9, 1])

In [294]:
x_reshaped.ndim

3

In [306]:
x_reshaped.unsqueeze(dim=2).shape

torch.Size([1, 9, 1, 1])

### Permute

In [324]:
x = torch.rand(size=(224, 224, 3))
x.shape

torch.Size([224, 224, 3])

In [325]:
x_permuted = x.permute(2, 0, 1)

In [326]:
x_permuted.shape

torch.Size([3, 224, 224])

In [327]:
x.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [342]:
x_permuted[0, 0, 0] = 1

In [343]:
x[0, 0, 0]

tensor(1.)

In [ ]:
# Permute also shares the same memory of the input, so changing x_permuted also changes x

### Indexing

In [357]:
x = torch.arange(1, 10).reshape(3, 1, 3)
x

tensor([[[1, 2, 3]],

        [[4, 5, 6]],

        [[7, 8, 9]]])

In [358]:
x[0]

tensor([[1, 2, 3]])

In [359]:
x[0, 0]

tensor([1, 2, 3])

In [360]:
x[0, 0, 0]

tensor(1)

In [361]:
x[1, 0, 1]

tensor(5)

In [387]:
x[:, :, 1]

tensor([[2],
        [5],
        [8]])

In [388]:
x[:, 0, :]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [391]:
x[0, 0, :]

tensor([1, 2, 3])

In [392]:
x[2, 0, 2]

tensor(9)

In [395]:
x[:, 0, 2]

tensor([3, 6, 9])

### pytorch and numpy

In [400]:
arr = np.arange(1., 8.)
tensor = torch.from_numpy(arr).type(torch.float32)

##### Note: _PyTorch's_ default dtype is `float32`, whereas _NumPy's_ default dtype is `float64`, so using `torch.from_numpy()` also makes the dtype `float64` use `.type(torch.float32)` to change back to default `float32`

In [401]:
arr.dtype, tensor.dtype

(dtype('float64'), torch.float32)

In [403]:
tensor = torch.ones(7)
numpy_arr = tensor.numpy()

In [404]:
tensor, numpy_arr

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [405]:
tensor.dtype, numpy_arr.dtype

(torch.float32, dtype('float32'))

##### Note: While changing _**NumPy**_ to _**PyTorch**_ (`torch.from_numpy(arr)`) or _**PyTorch**_ to _**NumPy**_ (`tensor.numpy()`), both the operations returns the _new items_ in the _memory_ with _new memory address_.

### Reproducibility (trying to taking out random out of random)

In [431]:
A = torch.rand(size=(3, 4))
B = torch.rand(size=(3, 4))

print(A)
print(B)
print(A == B)

tensor([[0.1155, 0.7824, 0.9867, 0.9495],
        [0.0249, 0.4212, 0.3521, 0.7177],
        [0.0945, 0.1024, 0.4333, 0.2194]])
tensor([[0.5794, 0.8188, 0.9083, 0.9304],
        [0.6069, 0.8368, 0.3743, 0.5770],
        [0.2553, 0.0041, 0.6624, 0.6269]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [457]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
D = torch.rand(3, 4)

print(C)
print(D)
print(C == D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### using GPU

In [476]:
!nvidia-smi

Wed Jun 17 23:54:03 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 610.47                 KMD Version: 610.47        CUDA UMD Version: 13.3     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   66C    P0             10W /   51W |     232MiB /   6144MiB |      7%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [477]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'